### PR TITLE
Fix RGBA decoding

### LINKED ISSUE #55: RGBA image results in "invalid maniac tree" for master branch
Example image can be downloaded from [here](https://github.com/dgriffen/flif.rs/files/2707292/incor.zip). Code in the `master` branch results in "invalid maniac tree", while `v0.3.0` published on crates.io correctly decompresses it. I guess we have introduced a bug somewhere together with optimizations.

### LINKED ISSUE #56: Incorrect decoding result of RGBA image with -K option
This [image](https://github.com/dgriffen/flif.rs/files/2708771/t.zip) produces an incorrect decoding result, while `flif` CLI tool decodes it correctly.

### LINKED ISSUE #58: Handle alpha_zero flag
`-K` option forces FLIF codec to keep RGB values for pixels with alpha=0. If we'll [encode](https://github.com/dgriffen/flif.rs/files/2710078/rust_logo_discard_invisible.zip) RGBA image (for example rust logo) without this option this crate will produce the following result:
rust_logo2

`flif` CLI tool produces correct output:
rust_logo3

Probably there is a bug in **alpha_zero** flag handling.

Note that this issue is different from #55, as image in it is encoded with `-K` option.

### PR DESCRIPTION
**Pull request by newpavlov**
Closes #55 
Closes #56 
Closes #58

Code had the following problems:
- Wrong channel order for MANIAC initialization was used. It should be RGBA, but I was using ARGB, the same as for channel passes.
- YCoCg transform wasn't calling next transform.
- With `alpha_zero == true` pixels with zero alpha value weren't skipped.
- Construction of `pvec` was slightly incorrect for RGBA image edges.

### CODE REVIEW

**Comment by newpavlov** [comment]
Note that it does not fix #56, I've tried to add these test [images](https://github.com/dgriffen/flif.rs/files/2708873/rust_logo.zip), but decoding result looks like this:
rust_logo2

File: flif/src/maniac/pvec.rs [hunk 1]
```diff
@@ -68,32 +68,32 @@ pub(crate) fn edge_pvec<P: Pixel>(pred: ColorValue, pvic: &EdgePixelVicinity<P>)
...
     // median index
-    pvec[i + 1] = match pred {
-        pred if pred == left + top - top_left => 0,
-        pred if pred == left => 1,
-        pred if pred == top => 2,
-        _ => 0,
-    };
-
-    if let Some(top_left) = pvic.top_left {
+    pvec[i + 1] = if let (Some(left), Some(top), Some(top_left)) =
```
Comment (dgriffen) [inline flif/src/maniac/pvec.rs]: Since pvec[i + 1] should already be 0 I think this should be changed to match the pattern of the other setters and only set when necessary.

File: flif/src/maniac/pvec.rs [hunk 2]
```diff
@@ -68,32 +68,32 @@ pub(crate) fn edge_pvec<P: Pixel>(pred: ColorValue, pvic: &EdgePixelVicinity<P>)
...
+        if pred == left + top - top_left { 0 }
+        else if pred == left { 1 }
+        else if pred == top { 2 }
+        else { 0 }
+    } else { 0 };
+
+    if let (Some(top_left), Some(left)) = (pvic.top_left, pvic.left) {
         pvec[i + 2] = left - top_left;
+    }
+    if let (Some(top_left), Some(top)) = (pvic.top_left, pvic.top) {
```
Comment (dgriffen) [inline flif/src/maniac/pvec.rs]: nit: add an empty line between if statements.

**Comment by newpavlov** [comment]
Done!

**Comment by dgriffen** [comment]
I'll cut a release sometime soon. I'll need to make an inventory of changes first. The minimum rustc version needed went up so this will be 0.4.

**Comment by newpavlov** [comment]
Any news regarding v0.4? Also taking the opportunity we may as well migrate to 2018 edition. I can prepare a PR with some clean-ups if you want.

**Comment by dgriffen** [comment]
Hi @newpavlov ! Sorry I've been super busy with some other projects recently. I'll probably do the 2018 migration myself, It'll be good practice.

**Comment by dgriffen** [comment]
@newpavlov, I finally published 0.4, sorry it took so long to get around to it.

**Comment by newpavlov** [comment]
Thanks! Though unfortunately you forgot about #48 (I can prepare a PR if you want) and edition bump. :) And maybe it will be worth to merge #52 as well? You could yank `v0.4.0` and publish `v0.4.1` with those changes, but it's not that important so it can stay as-is as well.

**Comment by dgriffen** [comment]
oh, right. Duh. I'll do that this weekend then.
